#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Enable or disable floating for specified windows

set -eu

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
WORKING_DIR="${XDG_CONFIG_HOME}/i3"
TEMP_DIR='/tmp/i3-auto-float.tmp'

print_error(){
	message="${1}"
	printf '%s\n' "Error: ${message}" >&2
	notify-send "Error: ${message}"
}

setup(){
	mkdir -p "${WORKING_DIR}/conf.d"
	touch "${WORKING_DIR}/conf.d/float.conf"
}

get_window_info(){
	current_active_window_id="$(xdotool getactivewindow)"
	current_window_class_info="$(xprop WM_CLASS -id "${current_active_window_id}")"
	current_window_class="$(printf '%s' "${current_window_class_info}" | cut -d ' ' -f 4 | tr -d '"')"
	current_window_instance="$(printf '%s' "${current_window_class_info}" | cut -d ' ' -f 3 | tr -d '"' | tr -d ',')"
}

modify_config(){
	if [ -z "${current_window_class}" ]; then
		print_error 'Window class not found.'
		return
	fi

	if [ -z "${current_window_instance}" ]; then
		print_error 'Window instance not found.'
		return
	fi

	if ! grep -q "${current_window_class}.*${current_window_instance}" "${WORKING_DIR}/conf.d/float.conf"; then
		printf '%s\n' "for_window [class=\"${current_window_class}\" instance=\"${current_window_instance}\"] floating enable" >> "${WORKING_DIR}/conf.d/float.conf"
		return
	fi

	sed "/^for_window \[class=\"${current_window_class}\" instance=\"${current_window_instance}\"\] floating enable$/d" "${WORKING_DIR}/conf.d/float.conf" > "${TEMP_DIR}"
	cp "${TEMP_DIR}" "${WORKING_DIR}/conf.d/float.conf"
}

reload(){
	i3-msg 'reload'
}

toggle_float(){
	i3-msg 'floating toggle'
}

main(){
	setup
	get_window_info
	modify_config
	reload
	toggle_float
}

main "${@}"

trap 'rm -f "${TEMP_DIR}"' EXIT INT QUIT TERM HUP
