#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Check for persistence before killing a window

# Env
set -e

setup(){
	XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
	workdir="$XDG_CONFIG_HOME"/i3

	mkdir -p "$workdir"/data
	touch "$workdir"/data/persist
}

run(){
	# Get current window info
	current_active_window_id="$(xdotool getactivewindow)"
	current_window_info="$(xprop -id "$current_active_window_id")"

	while IFS= read -r line; do
		# Ignore comments
		if printf '%s' "$line" | grep -q '^\s*#.*$'; then
			continue
		fi

		# Check if window is persisted
		if printf '%s' "$current_window_info" | grep -q -i "$line"; then
			# Send desktop notification
			notify-send 'i3' 'Persist on'
			return
		fi
	done < "$workdir"/data/persist

	# Kill window
	i3-msg 'kill'
}

main(){
	setup
	run
}

main "$@"
