#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Check for persistence before killing a window

set -e

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
WORKING_DIR="${XDG_CONFIG_HOME}/i3"

setup(){
	mkdir -p "${WORKING_DIR}/data"
	touch "${WORKING_DIR}/data/persist"
}

run(){
	current_active_window_id="$(xdotool getactivewindow)"
	current_window_info="$(xprop -id "${current_active_window_id}")"

	while IFS= read -r line; do
		# Ignore comments
		if printf '%s' "${line}" | grep -q '^\s*#.*$'; then
			continue
		fi

		# Check if window is persisted
		if printf '%s' "${current_window_info}" | grep -q -i "${line}"; then
			notify-send 'i3' 'Persist on'
			return
		fi
	done < "${WORKING_DIR}/data/persist"

	i3-msg 'kill'
}

main(){
	setup
	run
}

main "$@"
