#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Modular i3 config support

# Env
set -e
script_name="$(basename "${0}")"

print_error(){
	message="$1"
	echo "${script_name} - Error: ${message}" >&2
	notify-send "${script_name}" "Error: ${message}"
}

setup(){
	XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
	workdir="${XDG_CONFIG_HOME}"/i3
	TMP='/tmp/i3-modular-config.tmp'

	# Create necessary files and directories
	mkdir -p "$workdir"/conf.d
	mkdir -p "$workdir"/data
	touch "$workdir"/data/list
}

run(){
	# Clear tmp file
	cat /dev/null > "$TMP"

	# Looping through files in the list and Appending the output to tmp file
	while IFS= read -r x; do
		# Ignore comments and empty lines
		if printf '%s' "$x" | grep -q '^\s*\(#.*\|\)$'; then
			continue
		fi

		# Append content to tmp file
		cat "$workdir"/conf.d/"$x" >> "$TMP"
	done < "$workdir"/data/list

	# Check tmp file is empty
	if ! [ -s "$TMP" ]; then
		print_error 'Config file is empty.'
		return
	fi

	# Copy tmp file to config
	cp "$TMP" "$workdir"/config
}

main(){
	setup
	run
}

# Trap remove tmp file
trap 'rm -f "$TMP"' EXIT INT QUIT TERM HUP

main "$@"
