#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Modular i3 config support

# Env
set -e
script_name="$(basename $0)"
script_ver='v0.1'

print_error(){
	message="$1"
	echo "${script_name} - Error: ${message}" >&2
	notify-send "${script_name}" "Error: ${message}"
}

setup(){
	workdir="$XDG_CONFIG_HOME"/i3

	# Check XDG standard
	if [ -z "$XDG_CONFIG_HOME" ]; then
		workdir="$HOME"/.i3
	fi

	# Create necessary files and directories
	mkdir -p "$workdir"/configs
	mkdir -p "$workdir"/data
	touch "$workdir"/data/list

	# Create backup config
	if ! [ -f "$workdir"/config.bak ] && [ -f "$workdir"/config ]; then
		cp "$workdir"/config "$workdir"/config.bak
	fi
}

run(){
	# Clear i3 config file
	cat /dev/null > "$workdir"/config

	# Looping through files in the list and Appending the output to config
	while read x; do
		# Ignore comments
		if printf '%s' "$x" | grep -q '^\s*#.*$'; then
			continue
		fi

		# Check file found
		if ! [ -f "$workdir"/configs/"$x" ]; then
			print_error "${workdir}/configs/${x} not found."
			exit 1
		fi

		# Append content to config
		cat "$workdir"/configs/"$x" >> "$workdir"/config
	done < "$workdir"/data/list
}

main(){
	setup
	run
}

main "$@"
